# Generated by Django 4.0.6 on 2022-08-10 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reference_size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('abbreviation', models.CharField(max_length=15)),
                ('plural', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nutreint_name', to='api.name')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nutrient_unit', to='api.name')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('nutrients', models.ManyToManyField(to='api.nutrient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('serving_size', models.FloatField()),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.consumable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nutrient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.name')),
            ],
        ),
        migrations.AddField(
            model_name='consumable',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.consumablecategory'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='nutrients',
            field=models.ManyToManyField(to='api.nutrient'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.name'),
        ),
    ]
