# Generated by Django 4.0.6 on 2022-08-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablecategory',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.name'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nutrient_name', to='api.name'),
        ),
    ]
