# Generated by Django 4.0.6 on 2022-08-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dailyvalue_nutrient_unit_alter_consumable_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='nutrients',
            field=models.ManyToManyField(to='api.consumablenutrient'),
        ),
    ]
