# Generated by Django 4.0.6 on 2022-09-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_consumablenutrient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='plural',
            field=models.CharField(max_length=200),
        ),
    ]
