# Generated by Django 4.0.6 on 2022-10-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_nutrient_is_macronutrient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyvalue',
            name='nutrient',
        ),
        migrations.AddField(
            model_name='dailyvalue',
            name='nutrients',
            field=models.ManyToManyField(to='api.consumablenutrient'),
        ),
    ]
