# Generated by Django 4.0.6 on 2022-10-05 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_dailyvalue_nutrient_dailyvalue_nutrients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyvalue',
            name='value',
        ),
    ]
