# Generated by Django 4.0.6 on 2022-07-21 15:02

from django.db import migrations

FOOD_CATEGORIES = [
  'Breads and Grains',
  'Cereal',
  'Dairy',
  'Drink',
  'Fruit',
  'Meat',
  'Packaged Meal',
  'Packaged Snack',
  'Sauces and Spreads',
  'Supplement',
  'Vegetable',
]

def populate_food_categories(apps, schema_editor):
  FoodCategory = apps.get_model('app', 'FoodCategory')
  for category in FOOD_CATEGORIES:
    FoodCategory(name=category).save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220720_2033'),
    ]

    operations = [
      migrations.RunPython(populate_food_categories),
    ]
